### ISSUE TITLE
SNPSVM needs paired read to do variant calling?

### ISSUE THREAD

**Issue by jcollimore** [brendanofallon/SNPSVM#2]
use a single read BAM, it gives off following warning, and produces an VCF without calls.

Loading module class snpsvm.app.Predictor
Calling SNPs over 22556 bases with 4 threads in 1 chunks
java.lang.IllegalStateException: Inappropriate call if not paired read
        at net.sf.samtools.SAMRecord.requireReadPaired(SAMRecord.java:675)
        at net.sf.samtools.SAMRecord.getMateUnmappedFlag(SAMRecord.java:702)
        at snpsvm.bamreading.BamWindow.expand(BamWindow.java:263)
        at snpsvm.bamreading.BamWindow.advanceTo(BamWindow.java:169)
        at snpsvm.bamreading.AlignmentColumn.advanceTo(AlignmentColumn.java:173)
        at snpsvm.bamreading.ReferenceBAMEmitter.emitWindow(ReferenceBAMEmitter.java:149)
        at snpsvm.bamreading.SNPCaller.run(SNPCaller.java:75)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:679)

**Comment by brendanofallon** [comment]
Yep - right now SNPSVN assumes paired reads. This can be changed if we'd like without too much trouble - but we'd probably have to generate a new model as well.

**Comment by jcollimore** [comment]
OK, thank you for clarification. may you please add a single end read model?  This likely accommodates to more users with single end seq results. :-)
